add Julia readme
ustclug/mirrorhelp pull request #162
Opened 2020-10-07 20:13 UTC by johnnychen94

2020-10-07 20:14 UTC, johnnychen94 commented on source/julia.rst
> +  :sh:`miniconda`。 如果这一步下载非常缓慢的话，你可以提前从 `BFSU镜像站 <https://mirrors.bfsu.edu.cn/help/anaconda/>`_ 下载并安装 :sh:`anaconda`， 然后通过设置环境变量
这里提供了一个外链到 BFSU 镜像站，如果不想要的话可以删掉

2020-10-10 18:14 UTC, taoky requested changes

2020-10-10 18:14 UTC, taoky commented on source/julia.rst
> +.. code-block:: julia
这里标记为 `julia` 语言的除了最后一个代码块都不是 Julia 语句，会导致 `make html` 失败。

2020-10-10 18:14 UTC, taoky commented on source/julia.rst
> +  :sh:`miniconda`。 如果这一步下载非常缓慢的话，你可以提前从 `BFSU镜像站 <https://mirrors.bfsu.edu.cn/help/anaconda/>`_ 下载并安装 :sh:`anaconda`， 然后通过设置环境变量
这倒没什么问题，因为我们现在没有 Anaconda 的镜像……不过可以改成「从其他镜像站（如 BFSU 镜像站）」这样子。

2020-10-10 18:14 UTC, taoky commented on source/julia.rst
> +  （:sh:`\$HOME/anaconda3` 是 anaconda3 的默认安装位置， 你可能需要根据具体情况进行调整。）
这边是……多打了一个 `\`？

2020-10-10 18:14 UTC, taoky commented on source/julia.rst
> +  :sh:`CONDA_JL_HOME=$HOME/anaconda3` 来指定 :sh:`Conda.jl` 所使用的conda， 这样就避免重复下载 miniconda.
```suggestion
  :sh:`CONDA_JL_HOME=$HOME/anaconda3` 来指定 :sh:`Conda.jl` 所使用的 conda，这样就避免重复下载 miniconda.
```

2020-10-10 18:14 UTC, taoky commented on source/julia.rst
> +===================
此外 `index.rst` 文件也要编辑一下，在「语言镜像」那一块加上 julia。

2020-10-11 01:46 UTC, johnnychen94 commented
啊. 第一次写 rst 这些都不太清楚，谢谢指出。

文档的大部分内容来源于 https://github.com/tuna/mirror-web/blob/master/help/_posts/2020-05-25-julia.md

2020-10-11 08:50 UTC, taoky approved these changes

2020-10-11 08:52 UTC, merged