update ubuntu
ustclug/mirrorhelp pull request #170
Opened 2021-02-02 13:07 UTC by yuanyiwei

2021-02-02 14:23 UTC, taoky requested changes

2021-02-02 14:23 UTC, taoky commented on source/ubuntu.rst
> +和安全更新地址 ``http://security.ubuntu.com/`` 替换为 ``https://mirrors.ustc.edu.cn/`` 即可。
我不建议把安全更新和其他的放在一起，因为至少就 Debian 而言（Ubuntu 相关的我暂时没有找到资料），是不建议 security 用非 Debian 社区维护的镜像的，因为镜像站同步有延迟，而这对非常注重安全的生产环境系统来说是个很大的问题。

2021-02-02 14:50 UTC, yuanyiwei commented on source/ubuntu.rst
> +和安全更新地址 ``http://security.ubuntu.com/`` 替换为 ``https://mirrors.ustc.edu.cn/`` 即可。
那替换安全更新源改成可选项？
（但是下面 `sources.list` 样例是替换了安全更新源的

2021-02-02 15:52 UTC, taoky commented on source/ubuntu.rst
> +和安全更新地址 ``http://security.ubuntu.com/`` 替换为 ``https://mirrors.ustc.edu.cn/`` 即可。
可以加一个 `.. tip::` 块说一下这件事情。

2021-02-05 16:20 UTC, taoky approved these changes

2021-02-05 16:21 UTC, merged