增加设置默认镜像为科大镜像的方法
ustclug/mirrorhelp pull request #178
Opened 2021-05-11 19:48 UTC by Neutron3529

2021-05-12 00:05 UTC, ksqsf requested changes

2021-05-12 00:05 UTC, ksqsf commented on source/CRAN.rst
> +我们可以修改`$R_home/library/base/R/Rprofile`文件的第(28)行：
```suggestion
我们可以修改 `$R_home/library/base/R/Rprofile` 文件的第(28)行：
```

另外这个行号是否可以删掉？

2021-05-12 12:21 UTC, Neutron3529 commented on source/CRAN.rst
> +我们可以修改`$R_home/library/base/R/Rprofile`文件的第(28)行：
行号可以保留
这个文件很老，两年前就是第28行，现在（R 已经是4.0了）也是第28行，没必要修改

2021-05-13 04:41 UTC, ksqsf requested changes
感谢贡献！

不过 RST 格式仍然不正确（我们使用 reStructuredText 格式而不是 Markdown）。可以参考其他文档的写法（如 [archlinux](https://raw.githubusercontent.com/ustclug/mirrorhelp/master/source/archlinux.rst), [Julia](https://raw.githubusercontent.com/ustclug/mirrorhelp/master/source/julia.rst)），并在本地运行 `make html` 查看生成效果。

2021-05-15 00:01 UTC, merged

2021-05-15 00:02 UTC, ksqsf commented
good enough to go，感谢贡献！