修正 Cargo 文档（config文件路径）
ustclug/mirrorhelp pull request #181
Opened 2021-06-24 16:06 UTC by sky5454

2021-06-25 03:48 UTC, taoky commented
Hi,

reStructuredText 的语法与 Markdown 有所区别。请修复相关的编译问题（在配置环境后可使用 `make html` 进行测试）。

2021-06-25 03:55 UTC, taoky requested changes

2021-06-25 03:55 UTC, taoky commented on source/crates.io-index.rst
> +详见：https://doc.rust-lang.org/cargo/reference/config.html
```
42:Definition list ends without a blank line; unexpected unindent.
```

2021-06-25 03:55 UTC, taoky commented on source/crates.io-index.rst
> +`$CARGO_HOME/config` 默认是
https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#roles

https://docutils.sourceforge.io/docs/user/rst/quickref.html#inline-markup

2021-09-22 08:33 UTC, taoky commented
这几天在 Windows 上装了 Rust 的环境，看了一下这个 PR，感觉没有必要：

1. Windows 的 PowerShell 能够正确识别 `$HOME` 并且提供正确的环境变量。
2. 安装 Rust/Cargo 不会设置 `CARGO_HOME` 环境变量。

2021-09-22 08:33 UTC, closed without merging

2021-10-02 16:52 UTC, sky5454 commented
> 这几天在 Windows 上装了 Rust 的环境，看了一下这个 PR，感觉没有必要：
> 
> 1. Windows 的 PowerShell 能够正确识别 `$HOME` 并且提供正确的环境变量。
> 2. 安装 Rust/Cargo 不会设置 `CARGO_HOME` 环境变量。

用户可以设置

2021-10-02 17:11 UTC, taoky commented
> 用户可以设置

但是没有必要╮(╯▽╰)╭

如果要考虑 Windows 下还在用命令提示符的人的话……加个括号注释一下就行了，没有必要再引入一个新的环境变量（Windows 加环境变量还是有点麻烦，而且如果设置错了，[Cargo 是吃这个变量的](https://doc.rust-lang.org/cargo/reference/environment-variables.html?highlight=CARGO_HOME#environment-variables-cargo-reads)，徒增麻烦）。