更新ubuntu-cloud-images
ustclug/mirrorhelp pull request #186
Opened 2021-07-14 15:39 UTC by LengmoAngel

更新ubuntu-cloud-images

2021-07-14 16:17 UTC, taoky requested changes

2021-07-14 16:17 UTC, taoky commented on source/ubuntu-cloud-images.rst
> +收录由 Canonical 定制的为云服务设计的Ubuntu镜像，收录官方对 KVM、Hyper-V、Xen 等虚拟化平台的官方定制镜像，可在Openstack、LXD等的公共云上运行
```suggestion
收录由 Canonical 定制的为云服务设计的 Ubuntu 镜像，包含官方对 KVM、Hyper-V、Xen 等虚拟化平台的官方定制镜像，可在 Google Compute Engine、Amazon AWS 等公有云环境以及 OpenStack、LXD 等虚拟化平台上运行。
```

主要的几点：
1. 中文与英文之间应该有空格，与本仓库其他帮助文本相一致；
2. 文本需要符合中文语法与标点规范（句号）；
3. 软件名称拼写需要规范（Openstack -> OpenStack）；
4. 「公共云」指的是云服务厂商向公众提供的云服务（如阿里云、腾讯云、AWS 等等），OpenStack 与 LXD 不属于公共云的范畴。

2021-07-14 16:17 UTC, taoky commented on source/ubuntu-cloud-images.rst
> +.. todo :: ubuntu-cloud-images收录的使用说明
```suggestion
.. todo :: ubuntu-cloud-images 包括的虚拟化平台的镜像的使用说明
```

2021-07-15 06:15 UTC, LengmoAngel commented on source/ubuntu-cloud-images.rst
> +收录由 Canonical 定制的为云服务设计的Ubuntu镜像，收录官方对 KVM、Hyper-V、Xen 等虚拟化平台的官方定制镜像，可在Openstack、LXD等的公共云上运行
抱歉 没有注意到格式问题 已经修改了

2021-07-15 10:44 UTC, LengmoAngel commented
抱歉 没有注意到格式问题 已经修改了

2021-07-15 14:08 UTC, taoky commented on source/ubuntu-cloud-images.rst
> +收录由 Canonical 定制的为云服务设计的 Ubuntu 镜像，包含官方对 KVM、Hyper-V、Xen 等虚拟化平台的官方定制镜像，可在 Google Compute Engine、Amazon AWS 、Azure 环境以及 OpenStack、LXD 等虚拟化平台上运行。
```suggestion
收录由 Canonical 定制的为云服务设计的 Ubuntu 镜像，包含官方对 KVM、Hyper-V、Xen 等虚拟化平台的官方定制镜像，可在 Google Compute Engine、Amazon AWS、Azure 环境以及 OpenStack、LXD 等虚拟化平台上运行。
```

这里的小 typo 改一下我觉得就可以 merge 了。

2021-07-15 15:53 UTC, taoky approved these changes

2021-07-15 15:53 UTC, merged