Update opensuse.rst
ustclug/mirrorhelp pull request #194
Opened 2021-11-20 08:35 UTC by Mr-Ao-Dragon

小修改

2021-11-20 08:57 UTC, zhsj requested changes

2021-11-20 08:57 UTC, zhsj commented on source/opensuse.rst
> +**openSUSE Guide因为欠维护而过时，内容不能保证有效或有风险！**
hmm。。。如果openSUSE Guide内容有问题的话，可以在这里https://github.com/ustclug/opensuse-guide 提交issue，也欢迎提交PR。

2021-11-20 09:37 UTC, taoky requested changes

2021-11-20 09:37 UTC, taoky commented on source/opensuse.rst
> +* Tumbleweed 滚动发行版软件源的地址与上述例子稍有不同，一般为 [mirror site]/Tumbleweed/[file path]。
reStructuredText 的格式与 Markdown 不同，请 clone 仓库后 `make html` 验证修改有效性。

2021-11-20 09:37 UTC, taoky commented on source/opensuse.rst
> +  元数据），所以更改软件源通常只会加快刷新软件源的速度，而对下载速度影响不大，但对于经常滚动或重置的系统仍然有帮助（如 Kubic,MicroOS ）。
```suggestion
  元数据），所以更改软件源通常只会加快刷新软件源的速度，而对下载速度影响不大，但对于经常滚动或重置的系统仍然有帮助（如 Kubic、MicroOS）。
```

另外能否介绍一下 Kubic/MicroOS 与 OpenSUSE 的关系？

2021-11-20 09:37 UTC, taoky commented on source/opensuse.rst
> +建议 leap 15.3 用户不执行此操作，改为手动禁用以下命令对应的官方源，并添加以下源。
Why?

2021-11-20 09:44 UTC, taoky commented on source/opensuse.rst
> +* 我们不提供 backports, source 和 debug 源，如您需要，请考虑上海交通大学的镜像站。
```suggestion
* 我们不提供 backports, source 和 debug 源，如您需要，请考虑其他镜像站，提供 Ports 的镜像站列表参见 `openSUSE Mirrors 信息页 https://mirrors.opensuse.org/`_ 。
```

2021-11-20 09:55 UTC, Mr-Ao-Dragon commented on source/opensuse.rst
> +**openSUSE Guide因为欠维护而过时，内容不能保证有效或有风险！**
好的，谢谢你

2021-11-20 09:55 UTC, Mr-Ao-Dragon commented on source/opensuse.rst
> +* Tumbleweed 滚动发行版软件源的地址与上述例子稍有不同，一般为 [mirror site]/Tumbleweed/[file path]。
不是Markdown，而是原文如此。

2021-11-20 09:56 UTC, Mr-Ao-Dragon commented on source/opensuse.rst
> +建议 leap 15.3 用户不执行此操作，改为手动禁用以下命令对应的官方源，并添加以下源。
因为Leap还多了几个源，贸然禁用会导致问题

2021-11-20 09:57 UTC, Mr-Ao-Dragon commented on source/opensuse.rst
> +  元数据），所以更改软件源通常只会加快刷新软件源的速度，而对下载速度影响不大，但对于经常滚动或重置的系统仍然有帮助（如 Kubic,MicroOS ）。
一个相当于在容器运行的事物服务器，一个是风滚草k8s订制版

2021-11-20 09:59 UTC, Mr-Ao-Dragon commented on source/opensuse.rst
> +* 我们不提供 backports, source 和 debug 源，如您需要，请考虑上海交通大学的镜像站。
我看上去好像commit失败了，不知道为什么

2021-11-20 10:10 UTC, Mr-Ao-Dragon commented
所有修正看起来已完成，望合并，谢谢。

2021-11-20 10:29 UTC, taoky requested changes

2021-11-20 10:29 UTC, taoky commented on source/opensuse.rst
> +**openSUSE Guide因为欠维护而过时，内容不能保证有效或有风险！**
`/home/runner/work/mirrorhelp/mirrorhelp/source/opensuse.rst:92:Field list ends without a blank line; unexpected unindent.`

2021-11-20 10:29 UTC, taoky commented on source/opensuse.rst
>  :openSUSE Guide: https://lug.ustc.edu.cn/sites/opensuse-guide/
```suggestion
:openSUSE Guide（部分内容已过时）: https://lug.ustc.edu.cn/sites/opensuse-guide/
```

2021-11-20 10:45 UTC, zhsj commented on source/opensuse.rst
>  :openSUSE Guide: https://lug.ustc.edu.cn/sites/opensuse-guide/
所以哪些内容过时了？

2021-11-20 10:46 UTC, zhsj commented on source/opensuse.rst
>  :openSUSE Guide: https://lug.ustc.edu.cn/sites/opensuse-guide/
在 https://github.com/ustclug/opensuse-guide 提交issue说明下，再评估这里要不要说明它过时了。

2021-11-20 10:48 UTC, taoky commented on source/opensuse.rst
>  :openSUSE Guide: https://lug.ustc.edu.cn/sites/opensuse-guide/
OK，那 @Mr-Ao-Dragon 这个 PR 就先去掉关于 opensuse-guide 描述的修改吧。

2021-11-20 12:50 UTC, Mr-Ao-Dragon commented on source/opensuse.rst
>  :openSUSE Guide: https://lug.ustc.edu.cn/sites/opensuse-guide/
好的

2021-11-20 12:58 UTC, taoky commented on source/opensuse.rst
> +* Tumbleweed 滚动发行版软件源的地址与上述例子稍有不同，一般为 [mirror site]/Tumbleweed/[file path]。
L79 对应的例子需要修改为 <https://mirrors.ustc.edu.cn/opensuse/tumbleweed/>。

2021-11-21 04:36 UTC, Mr-Ao-Dragon commented
这次应该没问题了?

2021-11-21 06:48 UTC, taoky commented
> 这次应该没问题了?那再次申请合并

修改没有 push？

2021-11-22 02:37 UTC, Mr-Ao-Dragon commented
> > 这次应该没问题了?那再次申请合并
> 
> 修改没有 push？

没有，直接在线编辑并commit

2021-11-22 05:03 UTC, taoky commented
> > > 这次应该没问题了?那再次申请合并
> > 
> > 
> > 修改没有 push？
> 
> 没有，直接在线编辑并commit

您好，您没有合并在讨论中提及的全部修改（上一次 commit 为两天前）。

2021-11-22 07:54 UTC, Mr-Ao-Dragon commented
> > > > 这次应该没问题了?那再次申请合并
> > > 
> > > 
> > > 修改没有 push？
> > 
> > 没有，直接在线编辑并commit
> 
> 您好，您没有合并在讨论中提及的全部修改（上一次 commit 为两天前）。

已commit

2021-11-22 07:58 UTC, iBug commented
> reStructuredText 的格式与 Markdown 不同，请 clone 仓库后 `make html` 验证修改有效性。

见上

2021-11-22 08:10 UTC, Mr-Ao-Dragon commented
我还在装环境，哪位菊苣帮我编译下_(xз」∠)_

2021-11-22 08:50 UTC, taoky commented on source/opensuse.rst
> +建议 leap 15.3 用户不执行此操作，改为手动禁用以下命令对应的官方源，并添加以下源。
建议 leap 15.3 用户 => 建议 openSUSE Leap 15.3 或更高版本的用户

此外最好把这句新增的话移动到「禁用原有软件源」的后面。

2021-11-22 08:52 UTC, taoky commented
我 unresolve 了两个 conversation，需要进行进一步的讨论和修改。

2021-11-22 09:37 UTC, Mr-Ao-Dragon commented on source/opensuse.rst
> +建议 leap 15.3 用户不执行此操作，改为手动禁用以下命令对应的官方源，并添加以下源。
对rst语法不熟悉，怎么写注：格式呢?

2021-11-22 13:45 UTC, taoky requested changes

2021-11-22 13:45 UTC, taoky commented on source/opensuse.rst
> +建议 openSUSE Leap 15.3 用户不禁用所有软件源，而是手动禁用以上命令对应的官方源，并添加USTC提供的镜像站源。
```suggestion
建议 openSUSE Leap 15.3 用户不禁用所有软件源，而是手动禁用以上命令对应的官方源，并添加 USTC 提供的镜像站源。
```

或者

```suggestion
建议 openSUSE Leap 15.3 用户不禁用所有软件源，而是手动禁用以上命令对应的官方源，并添加中科大镜像源。
```

2021-11-22 13:45 UTC, taoky commented on source/packman.rst
> +openSUSE, SLE[Suse Linux Enterprise], fedora, ununtu, debian.
请注意，https://mirrors.ustc.edu.cn/packman/ 的 `debian` 和 `ubuntu` 目录是空的，里面没有包。

2021-11-22 13:45 UTC, taoky commented on source/packman.rst
> +====
`/path/to/mirrorhelp/source/packman.rst:16:Title underline too short.`

2021-11-22 13:45 UTC, taoky commented on source/opensuse.rst
> +* 如果您无法正常播放在线视频（例如爱奇艺），请尝试添加 `Packman 软件源 <http://mirrors.ustc.edu.cn/help/packman.html>`_ ，并安装VLC播放器。
```suggestion
* 如果您无法正常播放在线视频（例如爱奇艺），请尝试添加 `Packman 软件源 <http://mirrors.ustc.edu.cn/help/packman.html>`_ ，并安装 VLC 播放器。
```

另外安装 VLC 播放器和正常播放在线视频的关系是？播放视频应该安装的是解码器吧，要表达的意思是安装 VLC 的时候可以顺便安装视频解码器？

2021-11-22 13:45 UTC, taoky commented on source/opensuse.rst
> +* 对于非常古老的 openSUSE Leap，我们更建议您考虑升级系统以及依赖老版本的代码或软件。
这一条需要特地写在注意事项里面吗？可以参考其他的帮助（比如说 Fedora 的），在「收录架构」下面加上「收录版本：所有仍在支持的版本」？

2021-11-22 13:58 UTC, taoky commented on source/opensuse.rst
> +建议 leap 15.3 用户不执行此操作，改为手动禁用以下命令对应的官方源，并添加以下源。
> 对rst语法不熟悉，怎么写注：格式呢?

格式如：

```rst
.. warning::
    操作前请做好相应备份
```

渲染为网页的时候显示的效果参见 <https://mirrors.ustc.edu.cn/help/ubuntu.html#id7>

2021-11-22 14:02 UTC, Mr-Ao-Dragon commented on source/packman.rst
> +openSUSE, SLE[Suse Linux Enterprise], fedora, ununtu, debian.
好的

2021-11-22 14:03 UTC, Mr-Ao-Dragon commented on source/opensuse.rst
> +* 如果您无法正常播放在线视频（例如爱奇艺），请尝试添加 `Packman 软件源 <http://mirrors.ustc.edu.cn/help/packman.html>`_ ，并安装VLC播放器。
是的，这是最简便的方式，依赖会把解码器安装好

2021-11-22 14:04 UTC, Mr-Ao-Dragon commented on source/opensuse.rst
> +* 对于非常古老的 openSUSE Leap，我们更建议您考虑升级系统以及依赖老版本的代码或软件。
也不错?

2021-11-26 08:20 UTC, taoky commented
@Mr-Ao-Dragon 现在的 PR 还是有问题的，配置 Python 环境参考：

```shell
$ python3 -m venv .env
$ . .env/bin/activate
$ pip install -r requirements.txt
```

然后参考 <https://github.com/ustclug/mirrorhelp/blob/master/CONTRIBUTING.md#%E6%96%87%E6%A1%A3%E6%A0%BC%E5%BC%8F> 的介绍。

2023-03-27 13:57 UTC, closed without merging