fix ubuntu sed
ustclug/mirrorhelp pull request #212
Opened 2022-10-12 07:03 UTC by xiagw

2022-10-12 07:32 UTC, zhsj requested changes

2022-10-12 07:32 UTC, zhsj commented on source/ubuntu.rst
> +  sudo sed -i 's/\/\/.*archive.ubuntu.com/\/\/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
```suggestion
  sudo sed -i 's|//.*archive.ubuntu.com|//mirrors.ustc.edu.cn|g' /etc/apt/sources.list
```

没有转义，看起来更简单一些。。

2022-10-19 10:06 UTC, xiagw commented on source/ubuntu.rst
> +  sudo sed -i 's/\/\/.*archive.ubuntu.com/\/\/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
sudo sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list

2022-10-19 10:06 UTC, xiagw commented on source/ubuntu.rst
> +  sudo sed -i 's/\/\/.*archive.ubuntu.com/\/\/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
都可以

2022-11-26 16:43 UTC, jingjingxyk commented on source/ubuntu.rst
> +  sudo sed -i 's/\/\/.*archive.ubuntu.com/\/\/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
替换之前，先备份 /etc/apt/sources.list   文件 （用于多次换源)

```bash 

test -f /etc/apt/sources.list.save ||  cp /etc/apt/sources.list  /etc/apt/sources.list.save

```

2022-11-26 19:17 UTC, iBug commented on source/ubuntu.rst
> +  sudo sed -i 's/\/\/.*archive.ubuntu.com/\/\/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
此处命令上面已经写了“警告：操作前请做好相应备份”，就没有必要再给一个备份命令了

2022-11-27 08:18 UTC, taoky commented on source/ubuntu.rst
> +  sudo sed -i 's/\/\/.*archive.ubuntu.com/\/\/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
> 替换之前，先备份 /etc/apt/sources.list 文件 （用于多次换源)
> 
> 备份命令如下：
> 
> ```shell
> test -f /etc/apt/sources.list.save ||  cp /etc/apt/sources.list  /etc/apt/sources.list.save
> 
> 
> sed -i "s@security.ubuntu.com@mirrors.ustc.edu.cn@g" /etc/apt/sources.list 
> sed -i "s@archive.ubuntu.com@mirrors.ustc.edu.cn@g" /etc/apt/sources.list 
> ```

关于是否更改 security.ubuntu.com 的问题以及命令，帮助文档里面已经有明确说明。然后你的最后一条命令和现在仓库里的版本是等价的。

2022-11-27 08:19 UTC, taoky commented on source/ubuntu.rst
> +  sudo sed -i 's/\/\/.*archive.ubuntu.com/\/\/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
> sudo sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list

@xiagw 可以更新一下你的 PR 吗？把转义简化之后应该就能合了。

2022-11-28 12:22 UTC, merged