为archlinux 添加命令，实现一句命令添加镜像源
ustclug/mirrorhelp pull request #218
Opened 2022-12-31 07:05 UTC by jingjingxyk

为archlinux 添加命令，实现一句命令添加镜像源

2022-12-31 07:18 UTC, zhsj requested changes
sed -i.back 可以自动保存源文件。

2022-12-31 07:31 UTC, jingjingxyk commented
> sed -i.back 可以自动保存原文件。

修改好了 。

 `sed -i.back `  不好的地方就是：每次替换，都备份。 执行多次替换，备份文件其实已经不是最初的那个文件了。

2022-12-31 17:20 UTC, taoky requested changes

2022-12-31 17:20 UTC, taoky commented on source/archlinux.rst
> +    sed -i.backup '1 i  Server = https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch' /etc/pacman.d/mirrorlist
`i` 后面有个多余的空格

2023-01-01 03:30 UTC, jingjingxyk commented on source/archlinux.rst
> +    sed -i.backup '1 i  Server = https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch' /etc/pacman.d/mirrorlist
`i` 后的空格会被自动忽略的。

![image](https://user-images.githubusercontent.com/6836228/210160194-d1168bc2-ee9a-4c0a-90ed-4b964c4adf43.png)



之所以加空格，是为了让使用者容易看懂。



没改之前,命令还是这样呢
```shell

# 修改前备份一下 /etc/pacman.d/mirrorlist 文件

test -f /etc/pacman.d/mirrorlist.save || cp -f /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.save

# 执行添加，第一行之前插入

sed -i '1 i  Server = https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch' /etc/pacman.d/mirrorlist

```


包括使用 `i.backup`  我都觉得提高了使用门槛，因为 sed 不是特别熟悉的人，并不知道  `i.backup`  是为了备份源文件

![image](https://user-images.githubusercontent.com/6836228/210160226-79a3b8e2-2427-4954-9fb7-6199e77177c2.png)

2023-01-01 03:37 UTC, jingjingxyk commented on source/archlinux.rst
> +    sed -i.backup '1 i  Server = https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch' /etc/pacman.d/mirrorlist
> `i` 后面有个多余的空格

改好了

2023-01-01 04:41 UTC, zhsj commented on source/archlinux.rst
> +    sed -i.backup '1 i  Server = https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch' /etc/pacman.d/mirrorlist
> 包括使用 i.backup 我都觉得提高了使用门槛，因为 sed 不是特别熟悉的人，并不知道 i.backup 是为了备份源文件

那我觉得原来什么命令都不写的做法挺好的，代表每个人用自己想要的命令、想要的方法。

这本来就是arch的文档，用arch的人本身已经不是Linux小白了。

2023-01-01 04:44 UTC, zhsj requested changes

2023-01-01 04:44 UTC, zhsj commented on source/archlinuxcn.rst
> +    EOF
命令过于冗余

2023-01-01 06:07 UTC, jingjingxyk commented on source/archlinuxcn.rst
> +    EOF
> 命令过于冗余

请大佬赐教 。鄙人确实不知道其它写法

2023-01-02 13:16 UTC, taoky commented
我今天想了一下，对于 archlinux 和 archlinuxarm 这两项我的个人想法是：

1. [Arch Linux 安装指南](https://wiki.archlinux.org/title/Installation_guide#Boot_the_live_environment)中指出，可以使用 `mcedit`, `nano` 和 `vim` 编辑配置文件。考虑到安装 Arch 的过程就需要从网络获取软件包，并且在此时很难有直接复制粘贴的条件（Arch 官方并未提供包含图形界面的 LiveCD，而在 tty 里面从 w3m 之类复制命令出来……至少我不知道怎么做），手敲命令很容易出错，所以我不赞成不加提醒地提供「一句命令添加镜像」的帮助内容；
2. 但是，在诸如容器的场合，Arch 的官方 docker 镜像不包含文本编辑器，也可能存在需要在 Dockerfile 里配置的场景（虽然我从来没见过有人用 Arch 当应用容器镜像），在这种场景下提供命令可能会有帮助。

可以参考的文案：「Arch 的安装介质包含了例如 `nano` 的文本编辑器可以编辑配置文件。在不便于使用文本编辑器编辑配置的场合，可以在备份以上配置文件后，使用如下命令在对应文件行添加镜像配置：……」

关于 archlinuxcn，[中文的官方帮助](https://www.archlinuxcn.org/archlinux-cn-repo-and-mirror/)没有提供命令，并且其需要修改的是 `/etc/pacman.conf`，而不是 `/etc/pacman.d/mirrorlist`，如果出错了更难处理。所以我自己更倾向于不对其帮助做修改。

2023-10-30 06:38 UTC, closed without merging