fix(crates.io-index): fix config file path error when install rust without default CARGO_HOME environment variable
ustclug/mirrorhelp pull request #230
Opened 2023-07-08 04:55 UTC by cloudfstrife

cargo 安装时，如果没有指定 CARGO_HOME 时，默认的 CARGO_HOME 路径为 `~/.cargo` cargo 的配置文件路径 `$CARGO_HOME/config.toml`, 但是如果用户配置了 CARGO_HOME 环境变量，则配置文件的路径不再是 `~/.cargo/config.toml`，详细内容参见： [The Cargo Book Configuration](https://doc.rust-lang.org/cargo/reference/config.html#configuration)

PR修正了文本中的路径（使用 `$CARGO_HOME/config.toml` 替换 `~/.cargo/config`，原本的配置文件没有`.toml`后缀，不确定之前的文档是否正确）。并增加了 Linux 环境下写入配置文件的命令。

2023-07-08 05:43 UTC, taoky commented
关于 toml:

> Note: Cargo also reads config files without the .toml extension, such as .cargo/config. Support for the .toml extension was added in version 1.39 and is the preferred form. If both files exist, Cargo will use the file without the extension.

2023-07-08 05:47 UTC, taoky commented
然后需要考虑到看帮助的用户很可能不知道 `CARGO_HOME` 是什么意思——我建议在第一个备注上面加一些描述性文本指出其在 Windows 和 Unix 上的位置。

2023-07-08 06:05 UTC, cloudfstrife commented
@taoky 上面两个回复相关的内容已修正

2023-07-08 06:56 UTC, ksqsf requested changes

2023-07-08 06:56 UTC, ksqsf commented on source/crates.io-index.rst
> +在 :file:`$CARGO_HOME/config.toml` 中添加如下内容：
```suggestion
在 :file:`$CARGO_HOME/config` 中添加如下内容：
```

前后文应该保持一致

2023-07-08 07:48 UTC, taoky requested changes

2023-07-08 07:48 UTC, taoky commented on source/crates.io-index.rst
> +    cargo 1.68 版本开始支持稀疏索引：不再需要完整克隆 crates.io-index 仓库，可以加快获取包的速度。如果您的 cargo 版本大于等于 1.68，可以在 :file:`$CARGO_HOME/config` ( Windows 系统默认路径为: `%USERPROFILE%\.cargo\config` ,类 Unix 系统默认路径为: `$HOME/.cargo/
括号有点丑，可以改成前后无空格的全角括号吗？（可以参考 <https://github.com/ustclug/mirrorhelp/blob/master/source/debian.rst?plain=1#L63>）

2023-07-08 07:48 UTC, taoky commented on source/crates.io-index.rst
> +    cargo 1.68 版本开始支持稀疏索引：不再需要完整克隆 crates.io-index 仓库，可以加快获取包的速度。如果您的 cargo 版本大于等于 1.68，可以在 :file:`$CARGO_HOME/config` ( Windows 系统默认路径为: `%USERPROFILE%\.cargo\config` ,类 Unix 系统默认路径为: `$HOME/.cargo/
以及这个备注因为和下面的内容不在一个层级，建议在上面加一个 note 写。

2023-07-08 08:15 UTC, cloudfstrife commented
@taoky @ksqsf 我修改了整体的文件结构以使它更符合阅读习惯
首先是最基本的使用方法，然后是版本1.68+的稀疏索引的支持，最后是 warn 部分以及常见问题的解决方案

2023-07-08 08:19 UTC, taoky commented on source/crates.io-index.rst
> +    Windows 系统默认路径为: `%USERPROFILE%\.cargo\config`
```suggestion
    Windows 系统默认路径为: ``%USERPROFILE%\.cargo\config``
```

2023-07-08 08:22 UTC, taoky requested changes
（以及最后的小格式修改，别的我没有什么问题了）

2023-07-08 08:22 UTC, taoky commented on source/crates.io-index.rst
> +在 Linux 环境可以使用下面的命令完成
```suggestion
在 Linux 环境可以使用下面的命令完成：
```

2023-07-08 08:31 UTC, taoky commented on source/crates.io-index.rst
> +在 Linux 环境可以使用下面的命令完成
`":" != "："`

2023-07-08 09:43 UTC, ksqsf approved these changes
LGTM

2023-07-08 09:44 UTC, taoky approved these changes

2023-07-08 09:45 UTC, merged

2023-07-10 10:42 UTC, ZenithalHourlyRate commented
Could this be ported to https://github.com/mirrorz-org/mirrorz-help/blob/master/contents/crates.io-index.mdx

2023-07-10 10:50 UTC, taoky commented
> Could this be ported to https://github.com/mirrorz-org/mirrorz-help/blob/master/contents/crates.io-index.mdx

@cloudfstrife 有兴趣去 mirrorz-help 项目交 PR 吗？

2023-07-10 10:54 UTC, cloudfstrife commented
收到