Update proxmox.rst
ustclug/mirrorhelp pull request #232
Opened 2023-08-12 06:48 UTC by berlin2123

ceph for pve8

2023-08-12 07:02 UTC, taoky commented
我没有用过配置了 Ceph 的 PVE，不过我注意到 proxmox/debian/ 下面有好几个 ceph 版本，是不是把 ceph.list 里面的 download.proxmox.com 替换掉更合适？否则未来 ceph 版本号更新之后又要改帮助。

2023-08-12 07:19 UTC, berlin2123 commented
不错的建议，已修改

2023-08-12 08:18 UTC, iBug requested changes

2023-08-12 08:18 UTC, iBug commented on source/proxmox.rst
> +  sed -i 's|^deb https://enterprise.proxmox.com/debian/ceph|deb https://mirrors.ustc.edu.cn/proxmox/debian/ceph|g' /etc/apt/sources.list.d/ceph.list
建议 URL Path 这段相同的部分就略掉了（删掉 `/debian/ceph`）

2023-08-12 08:36 UTC, iBug requested changes

2023-08-12 08:36 UTC, iBug commented on source/proxmox.rst
> +  sed -i 's|^deb https://enterprise.proxmox.com/debian/ceph|deb https://mirrors.ustc.edu.cn/proxmox/debian/ceph|g' /etc/apt/sources.list.d/ceph.list
建议把 sed 命令里 URL path 里重复的部分删掉（`/debian/ceph`）

2023-08-13 08:16 UTC, berlin2123 commented
不再使用sed，sed只适用于未曾修改的原始source文件；如果之前已修改为其他mirror，最好直接替换整个文件。
新代码，已经可以自动匹配ceph的code name。

2023-08-13 08:20 UTC, taoky commented on source/proxmox.rst
> +修改 Ceph 源文件，可以使用如下命令：（从 PVE8 及之后版本需修改 Ceph 源， PVE7 及之前版本无需修改）
感觉这句话能改得表意更清楚一些，不过我先来改一下吧，之后如果都觉得没问题就合并。

2023-08-13 08:24 UTC, taoky commented on source/proxmox.rst
> +修改 Ceph 源文件，可以使用如下命令：（从 PVE8 及之后版本需修改 Ceph 源， PVE7 及之前版本无需修改）
@berlin2123 可以看一下我对这句话最新的修改。

2023-08-13 10:04 UTC, berlin2123 commented on source/proxmox.rst
> +修改 Ceph 源文件，可以使用如下命令：（从 PVE8 及之后版本需修改 Ceph 源， PVE7 及之前版本无需修改）
pve8 默认开启了ceph源的，（虽然用户可能根本不会使用ceph），新安装的用户，如果不改ceph源文件，apt update 就无法正常运行。因此这句话最好再改改

2023-08-13 10:05 UTC, taoky commented on source/proxmox.rst
> +修改 Ceph 源文件，可以使用如下命令：（从 PVE8 及之后版本需修改 Ceph 源， PVE7 及之前版本无需修改）
我虚拟机里装个看看吧。

2023-08-13 10:20 UTC, berlin2123 commented on source/proxmox.rst
> +修改 Ceph 源文件，可以使用如下命令：（从 PVE8 及之后版本需修改 Ceph 源， PVE7 及之前版本无需修改）
改成这样，也许就可以了：
PVE 8.0 及更高版本，可能需要修改 Ceph 仓库源文件：

2023-08-13 10:20 UTC, berlin2123 commented on source/proxmox.rst
> +修改 Ceph 源文件，可以使用如下命令：（从 PVE8 及之后版本需修改 Ceph 源， PVE7 及之前版本无需修改）
我这里的代码有判断命令：只有在那些启用过ceph源（存在ceph.list文件）的系统中，才会修改ceph源文件。
因此，即使有人在pve7上运行了这个命令，通常不会产生任何影响，除非他之前手动启用过ceph源。

2023-08-13 10:35 UTC, taoky commented on source/proxmox.rst
> +修改 Ceph 源文件，可以使用如下命令：（从 PVE8 及之后版本需修改 Ceph 源， PVE7 及之前版本无需修改）
确认了 PVE 8 安装器默认是装 ceph.list 的，那措辞确实得再微调一下。

2023-08-13 10:48 UTC, taoky commented on source/proxmox.rst
> +修改 Ceph 源文件，可以使用如下命令：（从 PVE8 及之后版本需修改 Ceph 源， PVE7 及之前版本无需修改）
@berlin2123 现在最新的描述应该是准确的了。

2023-08-13 13:14 UTC, iBug approved these changes

2023-08-14 05:50 UTC, taoky approved these changes

2023-08-15 05:02 UTC, merged